//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO_ESTADOS
    {
        public CONTRATO_ESTADOS()
        {
            this.CONTRATOS = new HashSet<CONTRATOS>();
        }
    
        public decimal ID_CONTRATO_ESTADO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
    }
}
