//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMA_PAGO
    {
        public FORMA_PAGO()
        {
            this.PAGOS = new HashSet<PAGOS>();
        }
    
        public decimal ID_FORMA_PAGO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> CANTIDAD_CUOTAS { get; set; }
    
        public virtual ICollection<PAGOS> PAGOS { get; set; }
    }
}
