//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOS
    {
        public SERVICIOS()
        {
            this.REPORTES = new HashSet<REPORTES>();
        }
    
        public decimal ID_SERVICIO { get; set; }
        public System.DateTime FECHA_HORA { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public decimal ID_TIPO_SERVICIO_FK { get; set; }
        public decimal ID_ESTADO_SERVICIOS_FK { get; set; }
        public decimal USUARIOS_ID_USUARIO { get; set; }
    
        public virtual ICollection<REPORTES> REPORTES { get; set; }
        public virtual SERVICIO_TIPOS SERVICIO_TIPOS { get; set; }
        public virtual SERVICIOS_ESTADO SERVICIOS_ESTADO { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
