//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_REPORTE
    {
        public TIPO_REPORTE()
        {
            this.REPORTES = new HashSet<REPORTES>();
        }
    
        public decimal ID_TIPO_REPORTE { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<REPORTES> REPORTES { get; set; }
    }
}
