//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public USUARIOS()
        {
            this.CHECKLIST = new HashSet<CHECKLIST>();
            this.SERVICIOS = new HashSet<SERVICIOS>();
        }
    
        public decimal ID_USUARIO { get; set; }
        public string RUT { get; set; }
        public string PATERNO { get; set; }
        public string MATERNO { get; set; }
        public string NOMBRES { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string EMAIL { get; set; }
        public string CLAVE { get; set; }
        public Nullable<int> CELULAR { get; set; }
        public Nullable<int> TELEFONO { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<short> ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public Nullable<decimal> ROLES_ID_ROL { get; set; }
    
        public virtual ICollection<CHECKLIST> CHECKLIST { get; set; }
        public virtual ROLES ROLES { get; set; }
        public virtual ICollection<SERVICIOS> SERVICIOS { get; set; }
    }
}
