//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARGO_EXTRA
    {
        public decimal ID_CARGO_EXTRA { get; set; }
        public string TIPO { get; set; }
        public decimal MONTO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> PAGOS_ID_PAGO { get; set; }
    
        public virtual PAGOS PAGOS { get; set; }
    }
}
