//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATOS
    {
        public decimal ID_CONTRATO { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_TERMINO { get; set; }
        public System.DateTime CREADO { get; set; }
        public Nullable<System.DateTime> MODIFICADO { get; set; }
        public long MONTO { get; set; }
        public decimal ID_CONTRATO_ESTADO_FK { get; set; }
        public Nullable<decimal> PAGOS_ID_PAGO { get; set; }
        public string RUT_CLIENTE { get; set; }
        public string RAZON_SOCIAL { get; set; }
    
        public virtual CONTRATO_ESTADOS CONTRATO_ESTADOS { get; set; }
        public virtual PAGOS PAGOS { get; set; }
    }
}
