//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGOS
    {
        public PAGOS()
        {
            this.CARGO_EXTRA = new HashSet<CARGO_EXTRA>();
            this.CONTRATOS = new HashSet<CONTRATOS>();
        }
    
        public decimal ID_PAGO { get; set; }
        public System.DateTime FECHA_HORA { get; set; }
        public long MONTO { get; set; }
        public System.DateTime CREADO { get; set; }
        public Nullable<System.DateTime> MODIFICADO { get; set; }
        public decimal FORMA_PAGO_ID_FORMA_PAGO { get; set; }
        public decimal CONTRATOS_ID_CONTRATO { get; set; }
    
        public virtual ICollection<CARGO_EXTRA> CARGO_EXTRA { get; set; }
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
        public virtual FORMA_PAGO FORMA_PAGO { get; set; }
    }
}
