//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTES
    {
        public decimal ID_REPORTE { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA_EMISION { get; set; }
        public decimal TIPO_REPORTE_ID_TIPO_REPORTE { get; set; }
        public decimal SERVICIOS_ID_SERVICIO { get; set; }
    
        public virtual SERVICIOS SERVICIOS { get; set; }
        public virtual TIPO_REPORTE TIPO_REPORTE { get; set; }
    }
}
